if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT is required")
endif()
file(TO_CMAKE_PATH "${ROOT}" ROOT)
file(READ "${ROOT}/stdlib/System/Compiler/GenForm.zan" genform)
file(READ "${ROOT}/tools/mcp_server/zform.doc.json" doc)

set(documented "")
foreach(section document fields columns)
  string(JSON count LENGTH "${doc}" ${section} keys)
  math(EXPR last "${count} - 1")
  if(last GREATER_EQUAL 0)
    foreach(i RANGE 0 ${last})
      string(JSON key GET "${doc}" ${section} keys ${i} key)
      list(APPEND documented "${key}")
    endforeach()
  endif()
endforeach()

string(REGEX MATCHALL "Obj(Str|Num|Bool)\\([^,]+,[ \t]*\"[^\"]+\"" object_matches "${genform}")
string(REGEX MATCHALL "\\.Get\\(\"[^\"]+\"" get_matches "${genform}")
set(source_keys "")
foreach(item IN LISTS object_matches get_matches)
  string(REGEX MATCH "\"([^\"]+)\"" key_match "${item}")
  if(key_match)
    string(REGEX REPLACE "^\"|\"$" "" key "${key_match}")
    list(APPEND source_keys "${key}")
  endif()
endforeach()
set(allowed_region_keys t x y w h r)
list(APPEND allowed_region_keys files)
# generator-request region (not .zform): the design request carries the
# component documents for ref expansion alongside the form files.
list(APPEND allowed_region_keys components)
foreach(key IN LISTS source_keys)
  list(FIND documented "${key}" found)
  list(FIND allowed_region_keys "${key}" region)
  if(found EQUAL -1 AND region EQUAL -1)
    message(FATAL_ERROR "GenForm reads undocumented .zform key: ${key}")
  endif()
endforeach()
foreach(key IN LISTS documented)
  list(FIND source_keys "${key}" found)
  if(found EQUAL -1 AND NOT key STREQUAL "on<Event>")
    message(FATAL_ERROR "zform.doc.json documents key no longer read by GenForm: ${key}")
  endif()
endforeach()

set(control_manifest "${ROOT}/tools/mcp_server/zform.controls.txt")
if(NOT EXISTS "${control_manifest}")
  message(FATAL_ERROR
    "generated control manifest is missing: ${control_manifest}; "
    "rerun scripts/gen_knowledge.ps1 to refresh the list")
endif()
file(STRINGS "${control_manifest}" listed_controls)
list(REMOVE_DUPLICATES listed_controls)
list(SORT listed_controls)

file(GLOB_RECURSE zan_files LIST_DIRECTORIES false "${ROOT}/stdlib/*.zan")
set(source_controls "")
set(props_regex "override[ \t]+List<PropSpec>[ \t]+Props[ \t]*\\(")
foreach(file IN LISTS zan_files)
  file(READ "${file}" text)
  string(REPLACE "\r\n" "\n" text "${text}")
  string(REPLACE "\n" ";" lines "${text}")
  unset(current_class)
  set(line_index 0)
  set(class_lines "")
  foreach(line IN LISTS lines)
    if(line MATCHES "^[ \t]*class[ \t]+([A-Za-z_][A-Za-z0-9_]*)")
      set(current_class "${CMAKE_MATCH_1}")
    endif()
    if(line MATCHES "${props_regex}")
      if(DEFINED current_class AND NOT current_class STREQUAL "")
        list(APPEND source_controls "${current_class}")
      endif()
    endif()
    math(EXPR line_index "${line_index}+1")
  endforeach()
endforeach()
list(REMOVE_DUPLICATES source_controls)
list(SORT source_controls)

foreach(name IN LISTS source_controls)
  list(FIND listed_controls "${name}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR
      "zform control manifest is missing class ${name}; "
      "rerun scripts/gen_knowledge.ps1 to refresh the list")
  endif()
endforeach()
foreach(name IN LISTS listed_controls)
  list(FIND source_controls "${name}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR
      "zform control manifest contains stale class ${name}; "
      "rerun scripts/gen_knowledge.ps1 to refresh the list")
  endif()
endforeach()
list(LENGTH source_controls control_count)
message(STATUS "zform schema OK: ${control_count} Props() control classes recognized")
