name: Upstream Sync

on:
  schedule:
    # 每天 UTC 0 点（北京时间早上 8 点）自动运行
    - cron: '*/5 * * * *'
  workflow_dispatch: # 保留手动触发按钮，方便测试

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出你自己的 Fork 仓库
      - name: Checkout target repo
        uses: actions/checkout@v4

      # 2. 使用 Sync Action 自动同步
      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          # 上游仓库的 owner/repo 格式，例如 alibaba/nacos
          upstream_sync_repo: joyspinch/zan-lang
          # 上游仓库的分支，通常是 main 或 master
          upstream_sync_branch: main
          # 你 Fork 仓库要更新的分支
          target_sync_branch: main
          # 使用 GitHub 自动生成的 Token 即可
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
